#!/bin/sh
'''exec' "/Users/jeevangowda/Desktop/AI Agent/venv/bin/python3.14" "$0" "$@"
' '''
import sys
from duckduckgo_search.cli import safe_entry_point
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(safe_entry_point())
